### ISSUE TITLE
New recipe / part 3

### ISSUE THREAD

**Issue by ddanilyuk** [DishBookOrg/DishBookIOS#6]
### Subtasks
- [ ] Create step view.
- [ ] Add modal controller with creating steps.
- [ ] To this modal controller add media picker.
- [ ] Also add time picker.

### Design

![image](https://user-images.githubusercontent.com/26975779/106792278-994f4480-665e-11eb-8e6d-80b5362eefa9.png)
![image](https://user-images.githubusercontent.com/26975779/106792298-a1a77f80-665e-11eb-828d-9d3a9315bb6c.png)
![image](https://user-images.githubusercontent.com/26975779/106792317-a835f700-665e-11eb-9435-30672f2a34b6.png)
